### ISSUE TITLE
xdg-document-portal spams my logs

### ISSUE THREAD

**Issue by LaurentBonnaud** [alexlarsson/xdg-document-portal#29]
Hi,

on my Ubuntu 17.10 system, logs are full of messages such as this one:

```
oct. 03 18:44:48 vougeot xdg-document-portal[14546]: unique: 10019, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 2796
oct. 03 18:44:48 vougeot xdg-document-portal[14546]:    unique: 10019, success, outsize: 96
```

Since a few days:
```
$ journalctl |grep xdg-document-portal|wc
 100565 1307342 10648428
```
and after a few hours of uptime after rebooting my system:
```
$ journalctl -b |grep xdg-document-portal|wc
  20743  269604 2197062
```

Here is version info:
```
Package: flatpak
Version: 0.9.98.1-0alexlarsson2~zesty
```

BTW, could you please add artful builds to your PPA?

**Comment by eMPee584** [comment]
Had the same issue. I created a `/etc/rsyslog.d/xdg-document-portal-noise.conf`:


`if $programname == "xdg-document-portal" and $msg contains "unique:" then       stop
`
then `systemctl restart rsyslog.service`. But how did this end up in a release anyway :sob: 

EDIT: ok fuse debug was left on (presumably by accident) since 4fdac9e5d4e0836b51ab22095439321a15e5f5fb (february 2017).. spam happens :rofl:

**Comment by LaurentBonnaud** [comment]
Thanks for the fix!
