### ISSUE TITLE
Files sometimes cannot be saved

### ISSUE THREAD

**Issue by fbruetting** [alexlarsson/xdg-document-portal#30]
Encountered this in Geary: https://gitlab.gnome.org/GNOME/geary/issues/145

When I want to save an attachment, this file just has 0 Bytes, but when I save it again and “overwrite” the old file, then it gets saved properly. You find more information and a stack trace in the linked bug report.

Furthermore, the start path of where to save that file (the path at which the portal opens) shouldn’t be a temporary directory of the Flatpak sandbox, but instead the user’s home directory (if this applies to the portal itself).

**Comment by alexlarsson** [comment]
I believe this is the same as:
https://github.com/flatpak/xdg-desktop-portal/issues/195
which is fixed in xdg-desktop-portal 1.0.3

Also, this repo is an old thing that is not used anymore, i'm gonna delete it. If you find the bug is not fixed in 1.0.3 please file a new issue at https://github.com/flatpak/xdg-desktop-portal/issues
